# Generated by Django 4.0.3 on 2025-04-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selloffdate', models.DateTimeField(blank=True, null=True)),
                ('quantitySold', models.PositiveIntegerField()),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalSellingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
                ('customerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasedate', models.DateTimeField(blank=True, null=True)),
                ('quantityPurchased', models.PositiveIntegerField()),
                ('buyingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalbuyingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buying_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
                ('supplierName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier')),
            ],
        ),
    ]
