# Generated by Django 4.0.3 on 2025-04-07 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_sale_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight_before',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchase'),
        ),
    ]
