# Generated by Django 5.2 on 2025-04-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_product_weight_before_product_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='purchase',
            new_name='quantitypurchased',
        ),
    ]
