# Generated by Django 5.2 on 2025-04-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_purchase_product_quantitypurchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight_after',
            new_name='driedWeight',
        ),
    ]
