# Generated by Django 5.2 on 2025-04-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_weight_after_product_driedweight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='selloffdate',
            new_name='sale_date',
        ),
    ]
