# Generated by Django 5.2 on 2025-04-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_sale_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='totalSellingPrice',
        ),
    ]
