# Generated by Django 5.2 on 2025-04-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_sale_totalsellingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_number',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
