# Generated by Django 5.2 on 2025-04-08 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_sale_sale_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='totalbuyingPrice',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_number',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchasedate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
