# Generated by Django 5.2 on 2025-04-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_purchase_totalbuyingprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
