# Generated by Django 5.2 on 2025-04-08 12:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_product_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='drying_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='drying_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantitypurchased',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchase'),
        ),
    ]
