# Generated by Django 5.2 on 2025-04-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_product_drying_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
