# Generated by Django 5.2 on 2025-04-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_sale_is_sold_alter_product_product_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
