# Generated by Django 5.2 on 2025-04-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_sale_is_sold_product_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
    ]
