# Generated by Django 5.2 on 2025-04-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_product_sold_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold_quantity',
        ),
    ]
