# Generated by Django 5.2 on 2025-04-15 08:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_product_initial_driedweight_saledetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='allocated_selling_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='dashboard.product'),
        ),
    ]
