# Generated by Django 5.2 on 2025-04-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_saledetail_allocated_selling_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchase'),
        ),
    ]
