# Generated by Django 5.2 on 2025-04-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_sale_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='allocated_selling_expenses',
        ),
    ]
