# Generated by Django 5.1.7 on 2025-04-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmproduce', '0002_remove_product_created_at_remove_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_kg',
            field=models.FloatField(verbose_name='Current stock (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=50, null=True),
        ),
    ]
